### PR TITLE
feat(win): Windows build support

### LINKED ISSUE #22: how to install pg_cron in Windows 10
Hello,

could I ask if there is any option to install pg_cron in PostgreSQL 9.6 which runs on my Windows 10 PC (operating system) ?

Thank you in advance!

Regards,
Vasilis

### LINKED ISSUE #323: installation on windows
hi . how can i use this extension on windows ?? i need this extension for pg_partman_bgw.interval change

### PR DESCRIPTION
**Pull request by codercms**
Inspired by https://github.com/pgvector/pgvector

Tested on Win 11, MSVS 2022 (MSVC 19), built for PostgreSQL 18

P.S. Also tested that it keep working on Ubuntu 24.04, built for PostgreSQL 17 (using clang 19)

P.P.S. Build fails on MINGW 64 for PostgreSQL 17+ but that's out of scope of this PR (its unrelated to changes introduced by this PR):
```
D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/15.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: src/pg_cron.o:pg_cron.c:(.text+0x158b): undefined reference to `libintl_ngettext'
collect2.exe: error: ld returned 1 exit status
make: *** [D:/msys64/mingw64/lib/postgresql/pgxs/src/makefiles/../../src/Makefile.shlib:319: pg_cron.dll] Error 1
```

But could be easy fixed by patching `Makefile`'s `SHLIB_LINK = $(libpq)` to `SHLIB_LINK = $(libpq) -lintl`

Closes #22
Closes #323

### CODE REVIEW

**Comment by codercms** [comment]
@microsoft-github-policy-service agree

**Comment by robe2** [comment]
I wasn't having this issue when I committed - #428 , things were working fine under windows, but now I am getting the same issue as you with below, so I'm guessing this issue came later

```
C:/ming64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: src/pg_cron.o: in function `GetTaskFeedback':
C:\ming64\projects\postgresql\extensions\pg_cron/src/pg_cron.c:1931:(.text+0x133e): undefined reference to `libintl_ngettext'
collect2.exe: error: ld returned 1 exit status
make: *** [C:/ming64/projects/POSTGR~1/rel/pg19w64/lib/pgxs/src/MAKEFI~1/../../src/Makefile.shlib:344: pg_cron.dll] Error 1
```


And yes simply patching that Makefile changing 

```SHLIB_LINK = $(libpq)``` to ```SHLIB_LINK = $(libpq) -lintl```

Works.  I've tested compiling under PostgreSQL 19beta1 with mingw. I haven't had a chance to run it under PG19 yet.

**Comment by marcoslot** [comment]
Thanks for contributing @codercms and testing @robe2 ! I'm unable to verify, so the validation really helps.

Can this be merged as is, or after the Makefile change?

**Comment by codercms** [comment]
@marcoslot that's high likely about Windows build under MINGW environment, this PR addresses build directly from Windows using MSVC compiler.
I could include a fix for MINGW too

**Comment by robe2** [comment]
@marcoslot  Confirmed this still compiles fine under mingw, however I still need to change the

SHLIB_LINK on Makefile 

from 
`SHLIB_LINK = $(libpq)`

to
`SHLIB_LINK = $(libpq) -lintl`


Perhaps that change if we confirm it doesn't break any Linux/Unix OS can be put in as a separate patch.

**Comment by robe2** [comment]
@marcoslot #437 fixes the mingw64 compile issue introduced  by a later commit.
